# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate] 
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://github.com/gugasp
baseurl: /dev/
title: Gustavo Araujo
author: Gustavo Araujo
description: Personal blog and resume
avatar: profile.png
email: seuemailaqui
github: s贸colarlink # username
linkedin: s贸colarlink
medium: s贸colarlink
codepen: s贸colarlink

#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
